/**
 * Bundle management for packx
 * Handles loading, saving, and analyzing file bundles in .pack/bundles/
 */

import { promises as fs } from "node:fs";
import * as path from "node:path";
import ignore from "ignore";

const BUNDLE_DIR = ".pack/bundles";

export type BundleDef = {
  name: string;
  path: string;
  patterns: string[];
};

export type BundleStats = {
  name: string;
  fileCount: number;
  tokenCount: number;
  matchCount: number;
};

/**
 * Ensure bundle directory exists
 */
export async function ensureBundleDir(rootDir: string): Promise<string> {
  const dir = path.join(rootDir, BUNDLE_DIR);
  try {
    await fs.mkdir(dir, { recursive: true });
  } catch {
    // Ignore if exists
  }
  return dir;
}

/**
 * Load all bundles from .pack/bundles directory
 */
export async function loadBundles(rootDir: string): Promise<BundleDef[]> {
  const bundlesDir = path.join(rootDir, BUNDLE_DIR);
  const bundles: BundleDef[] = [];

  try {
    const files = await fs.readdir(bundlesDir);
    for (const file of files) {
      if (file.endsWith(".bundle") || file.endsWith(".pack") || file.endsWith(".txt")) {
        try {
          const content = await fs.readFile(path.join(bundlesDir, file), "utf8");
          const patterns = content
            .split("\n")
            .map(l => l.trim())
            .filter(l => l && !l.startsWith("#"));

          // Clean name: "my-feature.bundle" -> "My Feature"
          const name = path.basename(file, path.extname(file))
            .replace(/[-_]/g, ' ')
            .replace(/\b\w/g, c => c.toUpperCase());

          bundles.push({
            name,
            path: path.join(bundlesDir, file),
            patterns
          });
        } catch {
          // Ignore read errors
        }
      }
    }
  } catch {
    // Directory doesn't exist, return empty
  }

  return bundles;
}

/**
 * Save a list of files as a bundle
 */
export async function saveBundle(rootDir: string, name: string, files: string[]): Promise<string> {
  const dir = await ensureBundleDir(rootDir);
  // Sanitize filename
  const safeName = name.replace(/[^a-zA-Z0-9-_]/g, '-').toLowerCase();
  const filePath = path.join(dir, `${safeName}.bundle`);

  const content = `# Bundle: ${name}
# Generated by packx
# Add patterns here (gitignore syntax)

${files.join("\n")}
`;

  await fs.writeFile(filePath, content, "utf8");
  return filePath;
}

/**
 * Calculate stats for bundles based on currently discovered files
 */
export function calculateBundleStats(
  bundles: BundleDef[],
  files: Array<{ relPath: string; tokens: number }>
): BundleStats[] {
  return bundles.map(bundle => {
    // Use ignore package to handle inclusion/exclusion logic
    const ig = ignore().add(bundle.patterns);

    let fileCount = 0;
    let tokenCount = 0;
    let matchCount = 0;

    for (const file of files) {
      // In gitignore syntax, ignores() returning true means it matches the pattern.
      // Since bundles are "inclusion lists", we count files that are "ignored" by the set.
      if (ig.ignores(file.relPath)) {
        fileCount++;
        tokenCount += file.tokens;
        matchCount++;
      }
    }

    return {
      name: bundle.name,
      fileCount,
      tokenCount,
      matchCount
    };
  });
}

/**
 * Get the set of indices for files matching a bundle
 */
export function getBundleFileIndices(
  bundle: BundleDef,
  files: Array<{ relPath: string }>
): Set<number> {
  const indices = new Set<number>();
  const ig = ignore().add(bundle.patterns);

  files.forEach((file, index) => {
    if (ig.ignores(file.relPath)) {
      indices.add(index);
    }
  });

  return indices;
}
